---
- name: Configure web server
  hosts: all
  become: true
- name: FTP server provisioning
  ansible.builtin.import_playbook: playbooks/ftp_config.yml
- name: DNS server provisioning
  ansible.builtin.import_playbook: playbooks/dns_config.yml
- name: DNS server provisioning
  ansible.builtin.import_playbook: playbooks/clients_dns_config.yml
