- name: Clientes Resolvs
  hosts: marte
  gather_facts: false
  become: true
  tasks:

    - name: Copiar configuracion resolv.conf
      copy:
        src: ../dns/dns_config_clients/marte/resolv.conf
        dest: /etc/resolv.conf