- name: Clientes Resolvs
  hosts: clients
  gather_facts: false
  become: true
  tasks:
    - name: Configure DNS settings for the clients
      copy:
        dest: /etc/resolv.conf
        content: |
          nameserver 192.168.56.103
          search sistema.sol