---
- name: Insercion de archivos
  hosts: tierra
  gather_facts: false
  become: true
  tasks:

    - name: Install bind9
      ansible.builtin.apt:
        name:
          - bind9
          - bind9-dnsutils
        state: present
        update_cache: true
      notify:
        - Restart and enable bind9

    - name: Copiar configuracion zona inversa
      ansible.builtin.copy:
        src: ../dns/db.56.168.192
        dest: /var/lib/bind/
        mode: '0644'
      notify:
        - Restart and enable bind9

    - name: Copiar configuracion zona directa
      ansible.builtin.copy:
        src: ../dns/db.sistema.sol
        dest: /var/lib/bind/
        mode: '0644'
      notify:
        - Restart and enable bind9

    - name: Copiar fichero named
      ansible.builtin.copy:
        src: ../dns/named
        dest: /etc/default/named
        mode: '0644'
      notify:
        - Restart and enable bind9

    - name: Copiar fichero named.conf.local
      ansible.builtin.copy:
        src: ../dns/named.conf.local
        dest: /etc/bind/named.conf.local
        mode: '0644'
      notify:
        - Restart and enable bind9

    - name: Copiar fichero named.conf.options
      ansible.builtin.copy:
        src: ../dns/named.conf.options
        dest: /etc/bind/named.conf.options
        mode: '0644'
      notify:
        - Restart and enable bind9

    - name: Resolv.conf configuration
      ansible.builtin.copy:
        dest: /etc/resolv.conf
        content: |
          nameserver 192.168.56.103
          search sistema.sol
          domain sistema.sol
        mode: '0644'
  handlers:
    - name: Restart and enable bind9
      ansible.builtin.service:
        name: bind9
        state: restarted
        enabled: true
