---
- name: Configure and Secure FTP Server
  hosts: mercurio
  become: yes
  tasks:
    - name: Install FTP client
      apt:
        name:
          - vsftpd
          - ftp
        state: present
        update_cache: yes
      notify:
        - Start and enable vsftpd
    - name: Backup the original config file for vsftpd
      copy:
        src: /etc/vsftpd.conf
        dest: /vagrant/ftp/backup_files/vsftpd.conf.bak
        remote_src: yes
      notify:
        - Start and enable vsftpd
    - name: Copy configuration file for vsftpd
      copy:
        src: ../ftp/config_files/vsftpd.conf
        dest: /etc/
      notify:
        - Start and enable vsftpd
    - name: Copy configuration file for chroot users
      copy:
        src: ../ftp/config_files/vsftpd.chroot_list
        dest: /etc/
      notify:
        - Start and enable vsftpd
    - name: Create user Luis
      ansible.builtin.user:
        name: luis
        shell: /bin/bash
        create_home: yes
        password: "$1$Aj2VMC5x$gyQo8Bx9JWS28r6aTlHHg/"
    - name: Create user Miguel
      ansible.builtin.user:
        name: miguel
        shell: /bin/bash
        create_home: yes
        password: "$1$Aj2VMC5x$gyQo8Bx9JWS28r6aTlHHg/"
    - name: Create user Maria
      ansible.builtin.user:
        name: maria
        shell: /bin/bash
        create_home: yes
        password: "$1$Aj2VMC5x$gyQo8Bx9JWS28r6aTlHHg/"
    - name: Create file1.txt in Luis's home directory
      copy:
        dest: /home/luis/luis1.txt
        content: |
          Luis's file number 1.
    - name: Create file2.txt in Luis's home directory
      copy:
        dest: /home/luis/luis2.txt
        content: |
          Luis's file number 2.
    - name: Create file1.txt in Maria's home directory
      copy:
        dest: /home/maria/maria1.txt
        content: |
          Maria's file number 1.
    - name: Create file2.txt in Maria's home directory
      copy:
        dest: /home/maria/maria2.txt
        content: |
          Maria's file number 2.
  handlers:
    - name: Start and enable vsftpd
      ansible.builtin.service:
        name: vsftpd
        state: restarted
        enabled: yes

