---
- name: Configure and Secure FTP Server
  hosts: localhost
  become: yes  # Execute with root privileges
  tasks:
    - name: Install FTP client
      apt:
        name: ftp
        state: present
      become: yes
  
    - name: Update Repository
      command: "sudo apt-get update"

    - name: Install vsftpd
      command: "sudo apt-get install vsftpd -y"

    - name: Verify if the ftp user exists
      command: "cat /etc/passwd | grep ftp"
      register: ftp_user_check
      failed_when: "'ftp' not in ftp_user_check.stdout"

    - name: Verify the FTP home directory
      command: "ls -ld /srv/ftp"
      register: ftp_home_check
      failed_when: "'/srv/ftp' not in ftp_home_check.stdout"

    - name: Configure initial permissions for the FTP directory
      command: "sudo chmod 755 /srv/ftp"

    - name: Backup the original configuration file
      command: "sudo cp /etc/vsftpd.conf /etc/vsftpd.conf.bak"

    - name: Customize the vsftpd server configuration
      blockinfile:
        path: /etc/vsftpd.conf
        marker: "# BEGIN CUSTOM CONFIGURATION"
        block: |
          listen=YES
          listen_ipv6=NO
          anonymous_enable=NO
          local_enable=YES
          write_enable=YES
          local_umask=022
          dirmessage_enable=YES
          use_localtime=YES
          xferlog_enable=YES
          connect_from_port_20=YES
          chroot_local_user=YES
          allow_writeable_chroot=YES
          rsa_cert_file=/etc/ssl/certs/vsftpd.pem
          rsa_private_key_file=/etc/ssl/private/vsftpd.key
          ssl_enable=YES
          allow_anon_ssl=NO
          force_local_data_ssl=YES
          force_local_logins_ssl=YES
          ssl_tlsv1=YES
          ssl_sslv2=NO
          ssl_sslv3=NO
          require_ssl_reuse=NO
          ssl_ciphers=HIGH

    - name: Create SSL certificates
      command: >
        openssl req -x509 -nodes -days 365 -newkey rsa:2048
        -keyout /etc/ssl/private/vsftpd.key
        -out /etc/ssl/certs/vsftpd.pem
        -subj "/C=AU/ST=State/L=City/O=Organization/OU=OrgUnit/CN=localhost"

      args:
        creates: /etc/ssl/certs/vsftpd.pem

    - name: Restart vsftpd to apply changes
      command: sudo systemctl restart vsftpd

    - name: Create user luis
      ansible.builtin.user:
        name: luis
        shell: /bin/bash
        create_home: yes
        password: ""
        state: present

    - name: Copy files of luis
      ansible.builtin.copy:
        src: /vagrant/usuarios/luis.txt
        dest: /home/luis
    
    - name: Create user maria
      ansible.builtin.user:
        name: maria
        shell: /bin/bash
        create_home: yes
        password: ""
        state: present

    - name: Copy files of maria
      ansible.builtin.copy:
        src: /vagrant/usuarios/maria.txt
        dest: /home/maria
    
    - name: Create user miguel
      ansible.builtin.user:
        name: miguel
        shell: /bin/bash
        create_home: yes
        password: ""
        state: present

    - name: Copy files of miguel
      ansible.builtin.copy:
        src: /vagrant/usuarios/miguel.txt
        dest: /home/miguel

    - name: Test anonymous FTP connection
      command: "ftp -p localhost"

    - name: Test authenticated FTP connection as luis
      command: "ftp -p localhost"

